export const devStartupSayings = [
  'Bringing Your Ads To Life.....',
  'Bringing your ads to life...',
  'Building your ads in real time...',
  'Shaping your ad experience...',
  'Assembling your ad creative...',
  'Spinning up your ad environment...',
  'Crafting your ad experience...',
  'Forming your ad units...',
  'Activating your ad development...',
  'Building out your ad system...',
  'Constructing your ad experience...',
  'Engineering your ad creative...',
  'Developing your ad units...',
  'Booting your ad development...',
  'Generating your ad experience...',
  'Producing your ad output...',
  'Initializing your ad system...',
  'Creating your ad experience...',
  'Compiling your ad experience...',
  'Building your ad framework...',
  'Preparing your ad system...',
  'Spinning up your ad runtime...',
  'Constructing your ad layout...',
  'Developing your ad environment...',
  'Bringing your ad system online...',
  'Building your ad pipeline...',
  'Generating your ad layout...',
  'Preparing your ad experience...',
  'Building your ad structure...',
  'Loading your ad framework...',
  'Spinning up your ad workspace...',
  'Activating your ad modules...',
  'Compiling your ad units...',
  'Constructing your ad assets...',
  'Building your ad runtime...',
  'Generating your ad system...',
  'Preparing your ad components...',
  'Initializing your ad experience...',
  'Building your ad interactions...',
  'Constructing your ad behavior...',
  'Activating your ad logic...',
  'Compiling your ad features...',
  'Generating your ad functionality...',
  'Preparing your ad logic...',
  'Building your ad interactions...',
  'Spinning up your ad logic...',
  'Constructing your ad system...',
  'Preparing your ad motion...',
  'Building your ad animations...',
  'Activating your ad transitions...',
  'Compiling your ad timing...',
  'Generating your ad movement...',
  'Constructing your ad animation...',
  'Preparing your ad states...',
  'Building your ad sequences...',
  'Spinning up your ad motion system...',
  'Activating your ad animation logic...',
  'Preparing your ad layout...',
  'Building your ad structure...',
  'Constructing your ad UI...',
  'Activating your ad layout system...',
  'Compiling your ad layout...',
  'Generating your ad interface...',
  'Preparing your ad components...',
  'Building your ad UI system...',
  'Spinning up your ad layout...',
  'Constructing your ad presentation...',
  'Aligning your ad system...',
  'Syncing your ad components...',
  'Bringing your ad pieces together...',
  'Driving your ad build forward...',
  'Completing your ad assembly...',
  'Preparing your ad output...',
  'Finalizing your ad framework...',
  'Completing your ad experience...',
  'Bringing your ads together...',
  'Almost ready with your ads...',
  'Completing your ad setup...',
  'Wrapping your ad experience...',
  'Preparing your ad for display...',
  'Finalizing yourw ad system...',
  'Completing your ad pipeline...',
  'Bringing your ads into focus...',
  'Preparing your ads for runtime...',
  'Readying your ad experience...',
];
