headline-1: Base <span class="red">Ad</span>
cta: Learn More
css-variables:
  colors:
    border-color: grey
    white: "#ffffff"
  images:
    image-1-url: url(./src/img/background.jpg)
  typography:
    headline-1-font-size: 50px
    headline-1-line-height: 110%
  other: {}
sprites:
  - name: sprite
