headline: We Make Awesome
cta: Learn More
cta-2: Hi
css-variables:
  colors:
    white: "#fff"
    border-color: grey
  images:
    photo-url: url(./src/img/photo-v1.jpg)
    photo-2-url: url(./src/img/photo-v2.jpg)
  typography:
    general-headline-font-size: 20px
    general-headline-line-height: 20px
  other:
    test-variable: test
    general-headline-test: test
    other-var: other
sprites:
  - name: sprite
