headline-1: Base Ad
cta: Learn More
css-variables:
  colors:
    white: "#fff"
    border-color: grey
  images:
    image-url: url(./src/img/background-v1.jpg)
  typography:
    headline-1-font-size: 30px
  other: {}
sprites:
  - name: sprite
