headline-1: Base <span class="red">Test</span>
cta: Learn More
css-variables:
  colors:
    border-color: grey
    white: "#fff"
  images:
    image-1-url: url(./src/img/background-v1.jpg)
  typography:
    headline-1-font-size: 30px
  other: {}
sprites:
  - name: sprite
