headline: Version 2 Headline
cta: Learn More
css-variables:
  photo-url: url(./src/img/photo-v2.jpg)
  general-headline-font-size: 10px
  white: "#ffffff"
  border-color: grey
  red: "#b32929"
sprites:
  - name: sprite
