headline: Version 3
cta: Learn More
css-variables:
  colors:
    white: "#ffffff"
    border-color: grey
    red: "#c63939"
  images:
    photo-url: url(./src/img/photo-v1.jpg)
    photo-2-url: url(./src/img/photo-v2.jpg)
  typography:
    general-headline-font-size: 37px
    general-headline-line-height: 20px
  other:
    test-variable: test
    general-headline-test: test
    other-var: other
